config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome', as: :welcome
get'/portfolio' => 'portfolio#portfolio', as: :portfolio
get'/blog' => 'blog#blog', as: :blog
get'/about' => 'about#about', as: :about
get'/contact' =>'contact#contact', as: :contact

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
def about
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
def blog
end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
def contact
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
    	
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
def portfolio
end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/about/about.html.erb
<div class="row">
    <div class="col-md-6">
        <img class="about-img" src="..//images/IMG_1008.JPG">
    </div>
    <div class="col-md-6 text-left">
        <h3>Hello. My name is <span class="hight-light">Nguyen Thi Hien </span></h3>
        <p>I was born in 1995 in Dong Nai province and raised in that before come to Ho Chi Minh city to learn.</p>
        <p>Since 2013, I've been done my favorite. Learn programing.</p>
    </div>
</div>

app/views/blog/blog.html.erb
<div class="wrapper">
		<form action="" method="post" name="loginnn" class="form-signin">       
		    <h3 class="form-signin-heading">Welcome Nguyen Thi Hien! </h3>
			  <hr class="colorgraph"><br>
			  
			  <input class="form-control" id= "email" name="Username" placeholder="Nhap email cua ban !" required="" autofocus="" type="text">
			  <input class="form-control" name="Password" placeholder="Password" required="" type="password">     		  
			 
			  <button class="btn btn-lg btn-primary btn-block" value="login" type="button" onclick="checkEmail();">Login</button>  			
		</form>			
</div>

app/views/contact/contact.html.erb
  <div class="row">
    <div class="col-md-12 text-right">
      <h1 class="contact-h1">Contact me</h1>
    </div>
   <div class="row">
     	<div class="col-md-2 col-sm-4 col-xs-6">
      	<a class="contact-linkedin contact-me" href="#">linkedin</a>
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
      	<a class="contact-github contact-me" href="https://github.com/hiennguyen123/">github</a>
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
      	<a class="contact-twitter contact-me" href="#">twitter</a>
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
      	<a class="contact-facebook contact-me" href="https://www.facebook.com/chimcanhcut3895">facebook</a>
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
      	<a class="contact-google-plus contact-me" href="https://mail.google.com/mail/u/0/?tab=wm#inbox/15069ab9f4c9667d">google plus</a>
      </div>
      <div class="col-md-2 col-sm-4 col-xs-6">
      	<a class="contact-instagram contact-me" href="#">instagram</a>
      </div>
   </div>
    
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,100,700,500' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<link rel="stylesheet" href="..//stylesheets/application.css">
<link rel="stylesheet" href="..//stylesheets/about.css">
<link rel="stylesheet" href="..//stylesheets/blog.css">
<link rel="stylesheet" href="..//stylesheets/contact.css">
<link rel="stylesheet" href="..//stylesheets/pages.css">
<link rel="stylesheet" href="..//stylesheets/portfolio.css">



<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="..//jquery-1.11.2.min.js"></script>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<%= stylesheet_link_tag "/stylesheets/style.css" %>
</head>
<body>
<div class = "header">
  <div class = "container">
    <div class = "row">
      <div class ="col-xs-8">
      <div class = "menu">
        <ul>
          <li><%= link_to "Welcome", welcome_path()%></li>
          <li><%= link_to "Portfolio", portfolio_path()%></li>
          <li><%= link_to "Blog", blog_path()%></li>
          <li><%= link_to "About", about_path()%></li>
          <li><%= link_to "Contact", contact_path()%></li>
        </ul>
      </div>
  </div>
      <div class ="col-xs-4">
      <div class = "name">
        <h1>Nguyễn Thị Hiền</h1>
    </div>
  </div>
</div>
</div>
<%= yield %>
<div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="socialmedia">
            <li><a class="twitter" href="#">twitter</a></li>
            <li><a class="linkedin" href="#">linkedin</a></li>
            <li><a class="github" href="#">github</a></li>
        	</ul>
        </div>
        <div class="clear"></div>
        <div class="col-md-12 text-right">
        	<p>&copy 2015 Nguyen Thi Hien</p>
        </div>
      </div>
        
    </div>
</div><script type="text/javascript"> function checkEmail() { var email = document.getElementById('email'); var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/; if (!filter.test(email.value)) { alert('Hay nhap dia chi email hop le.\nExample@gmail.com'); email.focus; return false; } else{ alert('Ban da dang nhap thanh cong');window.location="<%= welcome_path() %>" } } </script> 
</body>
</html>

app/views/pages/welcome.html.erb
<div class = "main_home">
  <div class = "jombotron">
    <div class = "container">
      <h2>My name is <span class = "hightlight" >Nguyen Thi Hien</span> and I have creative ideas and builds website</h2>
      <a class = "btn right" href = "/portfolio">View my Work</a>
    </div>
  </div>
</div>

app/views/portfolio/portfolio.html.erb
<script>

	$(document).ready(function() {
        $(window).scroll(function() {
             if ($(this).scrollTop() > 100)
			 {
				$('.nut1').fadeIn();	 
			 }
			 else
			 {
				$('.nut1').fadeOut();	 
			 }
        });
		$('.nut1').click(function() {
			$('html, body').animate({nut:0},800);
			
    });
	
		});
$(document).ready(function()
	{
		initbanner();
		$('#box').slideDown(1500,function()
		 {
			 setTimeout("$('#box').slideUp(1500)",1500) 
		 });
		
	});
	
	function initbanner()
	{
		if($(".slideshow div").length > 1) 
		{
			var transationTime = 2000;
			$(".slideshow div:first").addClass('active');  
			setInterval(slideChangeImage, transationTime); 
		}
	}
	
	
	function slideChangeImage()
	{
		var active = $(".slideshow div.active"); //Get the current active element.
		if(active.length == 0)
		{
			active = $(".slideshow div:last"); //If do not see the active element is the last image.
		}
		
		var next = active.next().length ? active.next() : $(".slideshow  div:first");
		active.addClass('lastactive');
		next.css({opacity:0.0})
				.addClass('active')
				.animate({opacity:1.0}, 1500, function()
				{
					active.removeClass("active lastactive"); 	
				});
	}

</script>

<div class="binh">
  <div class="banner">
        <div class="slideshow">
              <div><a href="#"><img src="..//images/slide1.jpg"/></a></div>
              <div><a href="#"><img src="..//images/slide2.jpg"/></a></div>
              <div><a href="#"><img src="..//images/slide3.jpg"/></a></div>
              <div><a href="#"><img src="..//images/slide4.jpg"/></a></div>
              <div><a href="#"><img src="..//images/slide5.jpg"/></a></div>
      </div>
  </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
         <a href="#" class="hinh">
          <div class="hinh-header">
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
          </div>
          <div class="hinh-image">
            <img src="..//images/project01-0ff155425c5a026839c43ae7c5089f1e.jpg">
          </div>
            <h3 class="hinh-hover">TravelGo’s Booking App</h3>
            <p class="hinh-hover">NGO liberal change-makers global time of extraordinary change, prevention climate change mobilize shift. Communities, social movement United Nations, Oxfam planned giving Global South humanitarian. Maximize.</p>
        </a>
      </div>

      <div class="col-md-6">
         <a href="#" class="hinh">
          <div class="hinh-header">
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
          </div>
          <div class="hinh-image">
            <img src="..//images/project02-ba5afb4eb817317b6be7ba2948be9fe3.jpg">
          </div>
            <h3 class="hinh-hover">Breather’s Reservation Site</h3>
            <p class="hinh-hover">Pursue these aspirations free-speech healthcare sharing economy freedom. Beneficiaries gender rights raise awareness change movements provide. Eradicate, diversification inspire breakthroughs, incubation; solve Peace Corps. Innovate.</p>
        </a>
      </div>

      <div class="col-md-6">
         <a href="#" class="hinh">
          <div class="hinh-header">
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
          </div>
          <div class="hinh-image">
           <img src="..//images/project03-f820dd50db97b4bef375e7645466b30e.jpg">
          </div>
            <h3 class="hinh-hover">EnVogue Events’ Portfolio</h3>
            <p class="hinh-hover">Informal economies; underprivileged, grantees transformative prosperity. Education best practices connect achieve plumpy'nut. Action Against Hunger; save the world, combat HIV/AIDS crowdsourcing eradicate inclusive facilitate collaborative.</p>
        </a>
      </div>

      <div class="col-md-6">
         <a href="#" class="hinh">
          <div class="hinh-header">
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
          </div>
          <div class="hinh-image">
            <img src="..//images/project04-1e66995d7e1fc884b9d84f6d9a2f135a.jpg">
          </div>
            <h3 class="hinh-hover">Gauntlet Gallery</h3>
            <p class="hinh-hover">Small-scale farmers; collaborative cities Bill and Melinda Gates best practices equity health theory of social change human experience. Tackle rural development relief worldwide respect, economic.</p>
        </a>
      </div>

      <div class="col-md-6">
         <a href="#" class="hinh">
          <div class="hinh-header">
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
          </div>
          <div class="hinh-image">
            <img src="..//images/project05-be5f6a9baca0191c49d4b424555f9287.jpg">
          </div>
            <h3 class="hinh-hover">Koi Pond Online Visitors Guide</h3>
            <p class="hinh-hover">UNICEF, research Ford Foundation outcomes collaborative consumption turmoil change lives. Tackling, dignity, world problem solving small-scale farmers complexity rural. Emergent humanitarian, necessities effect, challenges of.</p>
        </a>
      </div>

      <div class="col-md-6">
         <a href="#" class="hinh">
          <div class="hinh-header">
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
            <div class="hinh-header-decoration"></div>
          </div>
          <div class="hinh-image">
            <img src="..//images/project06-ec513d22a13d9c4c5f959882fa9ea7bb.jpg">
          </div>
            <h3 class="hinh-hover">Academy of Sciences  Newsletter</h3>
            <p class="hinh-hover">Aid collaborative global network overcome injustice honesty measures. Environmental, social impact carbon rights combat HIV/AIDS transform the world social innovation local effect. Free expression committed.</p>
        </a>
      </div>

    </div>
  </div>